//
//  DefaultStrings.swift
//  ClaudeBugPoC
//

import Foundation

// swiftlint:disable all
enum DefaultStrings: String {
    case tabPokemon = "tabs.main.pokemon"
    case tabMeals = "tabs.main.meals"
    case tabCountries = "tabs.main.countries"
    case tabLaunches = "tabs.main.launches"

    case commonErrorAlertTitle = "common.alert.error.title"
    case commonOkButton = "common.alert.ok"

    case aiAssistantTitle = "aiAssistant.title"
    case aiAssistantAccessibilityLabel = "aiAssistant.accessibilityLabel"
    case aiAssistantMenuContact = "aiAssistant.menu.contact"
    case aiAssistantMenuInspect = "aiAssistant.menu.inspect"
    case aiAssistantMenuFigmaCompare = "aiAssistant.menu.figmaCompare"
    case aiAssistantMenuFigmaCompareGemini = "aiAssistant.menu.figmaCompareGemini"

    case figmaCompareNavigationTitle = "figmaCompare.navigationTitle"
    case figmaCompareNavigationTitleGemini = "figmaCompare.navigationTitle.gemini"
    case figmaCompareUrlInputTitle = "figmaCompare.urlInput.title"
    case figmaCompareUrlInputSubtitle = "figmaCompare.urlInput.subtitle"
    case figmaCompareUrlInputPlaceholder = "figmaCompare.urlInput.placeholder"
    case figmaCompareSubmitButton = "figmaCompare.button.submit"
    case figmaComparePickImageButton = "figmaCompare.button.pickImage"
    case figmaComparePickImageSheetTitle = "figmaCompare.pickImage.sheetTitle"
    case figmaComparePickImagePhotos = "figmaCompare.pickImage.photos"
    case figmaComparePickImageFiles = "figmaCompare.pickImage.files"
    case figmaCompareImageReadError = "figmaCompare.error.imageRead"
    case figmaCompareCancelButton = "figmaCompare.button.cancel"
    case figmaCompareLoadingMessage = "figmaCompare.loading.message"
    case figmaCompareResultTitle = "figmaCompare.result.title"
    case figmaCompareResultEmpty = "figmaCompare.result.empty"
    case figmaCompareErrorInvalidURL = "figmaCompare.error.invalidURL"
    case figmaCompareErrorFormat = "figmaCompare.error.format"
    case figmaCompareUnexpectedResponse = "figmaCompare.error.unexpectedResponse"
    case figmaCompareDetectedScreenFormat = "figmaCompare.detectedScreen.format"
    case figmaCompareMetadataFormat = "figmaCompare.metadata.format"
    case figmaCompareCategoryLayout = "figmaCompare.category.layout"
    case figmaCompareCategoryColor = "figmaCompare.category.color"
    case figmaCompareCategoryTypography = "figmaCompare.category.typography"
    case figmaCompareCategorySpacing = "figmaCompare.category.spacing"
    case figmaCompareCategoryMissing = "figmaCompare.category.missing"
    case figmaCompareCategoryExtra = "figmaCompare.category.extra"
    case figmaCompareCategoryIcons = "figmaCompare.category.icons"
    case figmaCompareCategoryOther = "figmaCompare.category.other"
    case figmaCompareSeverityHigh = "figmaCompare.severity.high"
    case figmaCompareSeverityMedium = "figmaCompare.severity.medium"
    case figmaCompareSeverityLow = "figmaCompare.severity.low"

    case aiInspectorTitle = "aiInspector.title"
    case aiInspectorHint = "aiInspector.hint"
    case aiInspectorClose = "aiInspector.close"
    case aiInspectorLocalizationKeyLabel = "aiInspector.localizationKey.label"
    case aiInspectorBackendValueLabel = "aiInspector.backendValue.label"
    case aiInspectorEmptyText = "aiInspector.emptyText"

    case aiChatNavigationTitle = "aiChat.navigationTitle"
    case aiChatWelcomeMessage = "aiChat.welcome.message"
    case aiChatInputPlaceholder = "aiChat.input.placeholder"
    case aiChatSendButton = "aiChat.button.send"
    case aiChatCreatePRButton = "aiChat.button.createPR"
    case aiChatNoChangesApproved = "aiChat.message.noChangesApproved"
    case aiChatDescribeBugFirst = "aiChat.message.describeBugFirst"
    case aiChatErrorFormat = "aiChat.message.error.format"
    case aiChatAnalyzing = "aiChat.message.analyzing.format"
    case aiChatJobTimeout = "aiChat.message.jobTimeout"
    case aiChatUnexpectedResponse = "aiChat.message.unexpectedResponse"
    case aiChatNoResponse = "aiChat.message.noResponse"
    case aiChatMetadataFormat = "aiChat.message.metadata.format"
    case aiChatCacheMetadata = "aiChat.message.metadata.cache"
    case aiChatTechnicalSeparator = "aiChat.message.technicalSeparator"
    case aiChatNoCodeChange = "aiChat.message.noCodeChange"
    case aiChatTechnicalDetailFormat = "aiChat.message.technicalDetail.format"
    case aiChatJiraError = "aiChat.message.jiraError.format"
    case aiChatJiraInvalidResponse = "aiChat.message.jiraInvalidResponse"
    case aiChatSprintAdded = "aiChat.message.sprintAdded.format"
    case aiChatPRError = "aiChat.message.prError.format"
    case aiChatPRInvalidResponse = "aiChat.message.prInvalidResponse"
    case aiChatPROpened = "aiChat.message.prOpened.format"
    case aiChatDiffNoChanges = "aiChat.diff.noChanges"
    case aiChatRoleUser = "aiChat.role.user"
    case aiChatRoleAssistant = "aiChat.role.assistant"
    case aiChatRoleSystem = "aiChat.role.system"
    case aiChatProposedChangeHeader = "aiChat.proposedChange.header"
    case aiChatAcceptChange = "aiChat.proposedChange.accept"
    case aiChatRejectChange = "aiChat.proposedChange.reject"
    case aiChatAcceptedChange = "aiChat.proposedChange.accepted"
    case aiChatRejectedChange = "aiChat.proposedChange.rejected"
    case aiChatActionPrompt = "aiChat.action.prompt"
    case aiChatBugActionTitle = "aiChat.action.bug.title"
    case aiChatBugActionSubtitle = "aiChat.action.bug.subtitle"
    case aiChatCodeActionTitle = "aiChat.action.code.title"
    case aiChatCodeActionSubtitle = "aiChat.action.code.subtitle"
    case aiChatJiraCreating = "aiChat.jira.creating"
    case aiChatJiraCreated = "aiChat.jira.created"
    case aiChatJiraNoChangeSuffix = "aiChat.jira.noChangeSuffix"
    case aiChatJiraChangesBelowSuffix = "aiChat.jira.changesBelowSuffix"
    case aiChatJiraTicketHeader = "aiChat.jira.ticketHeader"
    case aiChatOpenJira = "aiChat.jira.openButton"

    case pokemonHeight = "pokemon.detail.height"
    case pokemonWeight = "pokemon.detail.weight"
    case pokemonStats = "pokemon.detail.stats"

    case mealsYoutube = "meals.detail.youtube"
    case mealsIngredients = "meals.detail.ingredients"
    case mealsInstructions = "meals.detail.instructions"
    case mealsNoInstructions = "meals.detail.noInstructions"

    case countriesOpenMap = "countries.detail.openMap"
    case countriesCapital = "countries.detail.capital"
    case countriesRegion = "countries.detail.region"
    case countriesPopulation = "countries.detail.population"
    case countriesArea = "countries.detail.area"
    case countriesLanguages = "countries.detail.languages"
    case countriesCurrency = "countries.detail.currency"
    case countriesTimezone = "countries.detail.timezone"
    case countriesBorders = "countries.detail.borders"

    case launchesWebcast = "launches.detail.webcast"
    case launchesArticle = "launches.detail.article"
    case launchesWikipedia = "launches.detail.wikipedia"
    case launchesFlightFormat = "launches.detail.flight.format"
}

extension DefaultStrings {
    var fallback: String {
        switch self {
        case .tabPokemon: return "Pokémon"
        case .tabMeals: return "Tarifler"
        case .tabCountries: return "Ülkeler"
        case .tabLaunches: return "Uzay"

        case .commonErrorAlertTitle: return "Hata"
        case .commonOkButton: return "Tamam"

        case .aiAssistantTitle: return "AI Asistan"
        case .aiAssistantAccessibilityLabel: return "AI Asistan"
        case .aiAssistantMenuContact: return "💬  AI ile İletişime Geç"
        case .aiAssistantMenuInspect: return "🔍  Ekrandaki ID'leri Gör"
        case .aiAssistantMenuFigmaCompare: return "🎨  Figma ile Karşılaştır (Claude)"
        case .aiAssistantMenuFigmaCompareGemini: return "✨  Figma ile Karşılaştır (Gemini)"

        case .figmaCompareNavigationTitle: return "Figma Karşılaştır"
        case .figmaCompareNavigationTitleGemini: return "Figma Karşılaştır (Gemini)"
        case .figmaCompareUrlInputTitle: return "Figma Frame URL'ini Yapıştır"
        case .figmaCompareUrlInputSubtitle: return "Bulunduğun ekran ile Figma'daki frame karşılaştırılacak. Frame'i Figma'da sağ tık → Copy link to selection ile alabilirsin."
        case .figmaCompareUrlInputPlaceholder: return "https://www.figma.com/design/..."
        case .figmaCompareSubmitButton: return "Karşılaştır"
        case .figmaComparePickImageButton: return "🖼️ Bunun yerine PNG yükle"
        case .figmaComparePickImageSheetTitle: return "Görseli nereden seçeceksin?"
        case .figmaComparePickImagePhotos: return "Fotoğraflar"
        case .figmaComparePickImageFiles: return "Dosyalar"
        case .figmaCompareImageReadError: return "❌ Görsel okunamadı ya da çok büyük (en fazla 5MB)."
        case .figmaCompareCancelButton: return "İptal"
        case .figmaCompareLoadingMessage: return "Ekran karşılaştırılıyor..."
        case .figmaCompareResultTitle: return "Karşılaştırma Sonucu"
        case .figmaCompareResultEmpty: return "✅ Belirgin bir fark bulunamadı."
        case .figmaCompareErrorInvalidURL: return "❌ Geçerli bir Figma frame URL'i değil. URL şu formatta olmalı: https://www.figma.com/design/<fileId>/...?node-id=<nodeId>"
        case .figmaCompareErrorFormat: return "❌ Hata: {message}"
        case .figmaCompareUnexpectedResponse: return "❌ Beklenmedik response formatı"
        case .figmaCompareDetectedScreenFormat: return "📱 Karşılaştırılan ekran: {screen}"
        case .figmaCompareMetadataFormat: return "📊 {iterations} iterasyon · 🪙 {inputTokens}+{outputTokens} token · 💵 ${cost}"
        case .figmaCompareCategoryLayout: return "📐 Layout"
        case .figmaCompareCategoryColor: return "🎨 Renk"
        case .figmaCompareCategoryTypography: return "🔤 Tipografi"
        case .figmaCompareCategorySpacing: return "📏 Spacing"
        case .figmaCompareCategoryMissing: return "❌ Eksik Element"
        case .figmaCompareCategoryExtra: return "➕ Fazla Element"
        case .figmaCompareCategoryIcons: return "🖼️ İkon / Görsel"
        case .figmaCompareCategoryOther: return "ℹ️ Diğer"
        case .figmaCompareSeverityHigh: return "🔴 Yüksek"
        case .figmaCompareSeverityMedium: return "🟡 Orta"
        case .figmaCompareSeverityLow: return "🟢 Düşük"

        case .aiInspectorTitle: return "Eleman Detayı"
        case .aiInspectorHint: return "Detayını görmek istediğin elemana dokun"
        case .aiInspectorClose: return "Kapat"
        case .aiInspectorLocalizationKeyLabel: return "Localization Key"
        case .aiInspectorBackendValueLabel: return "Backend Değeri"
        case .aiInspectorEmptyText: return "(metin yok)"

        case .aiChatNavigationTitle: return "Claude Bug Analyzer"
        case .aiChatWelcomeMessage:
            return "👋 Uygulamada gördüğün bir sorunu sade bir dille anlat.\n\nClaude sorunu özetleyip iki seçenek sunar:\n🐛 Bug Aç — Jira'da otomatik ticket açar\n🛠️ Kodu Düzenle — önerilen kod değişikliklerini gösterir, beğenirsen PR oluşturur"
        case .aiChatInputPlaceholder: return "Bug'ı tarif et..."
        case .aiChatSendButton: return "Gönder"
        case .aiChatCreatePRButton: return "🚀 PR Oluştur"
        case .aiChatNoChangesApproved: return "ℹ️ Hiçbir değişiklik ✓ ile onaylanmadı. PR açılmadı."
        case .aiChatDescribeBugFirst: return "❌ Önce bir bug tarif etmelisin."
        case .aiChatErrorFormat: return "❌ Hata: {message}\nCode: {code}\nDomain: {domain}"
        case .aiChatAnalyzing: return "🔄 Analiz ediliyor… ({iterations}. adım)"
        case .aiChatJobTimeout: return "⏱️ Analiz beklenenden uzun sürdü ve zaman aşımına uğradı. Lütfen tekrar dener misin?"
        case .aiChatUnexpectedResponse: return "❌ Beklenmedik response formatı"
        case .aiChatNoResponse: return "(Claude bir cevap üretemedi)"
        case .aiChatMetadataFormat: return "📊 {iterations} iterasyon · 🪙 {inputTokens}+{outputTokens} token · 💵 ${cost}"
        case .aiChatCacheMetadata: return "♻️ cache: {read} read · {write} write"
        case .aiChatTechnicalSeparator: return "---TEKNİK---"
        case .aiChatNoCodeChange: return "ℹ️ Claude bu bug için somut bir kod değişikliği önermedi."
        case .aiChatTechnicalDetailFormat: return "🔧 Teknik detay:\n\n{detail}"
        case .aiChatJiraError: return "❌ Jira ticket oluşturulamadı: {message}"
        case .aiChatJiraInvalidResponse: return "❌ Jira yanıtı beklenen formatta değil"
        case .aiChatSprintAdded: return "✅ Aktif sprint'e eklendi: {sprintName}"
        case .aiChatPRError: return "❌ PR oluşturulamadı: {message}"
        case .aiChatPRInvalidResponse: return "❌ PR yanıtı beklenen formatta değil"
        case .aiChatPROpened: return "✅ PR #{number} açıldı\n🌿 branch: {branch}\n🔗 {url}"
        case .aiChatDiffNoChanges: return "(değişiklik yok)"
        case .aiChatRoleUser: return "🧑 SEN"
        case .aiChatRoleAssistant: return "🤖 CLAUDE"
        case .aiChatRoleSystem: return "ℹ️  SYSTEM"
        case .aiChatProposedChangeHeader: return "📝 ÖNERİLEN DEĞİŞİKLİK"
        case .aiChatAcceptChange: return "✓ Ekle"
        case .aiChatRejectChange: return "✗ Atla"
        case .aiChatAcceptedChange: return "✓ EKLENECEK"
        case .aiChatRejectedChange: return "✗ ATLANDI"
        case .aiChatActionPrompt: return "Şimdi ne yapmak istersin?"
        case .aiChatBugActionTitle: return "🐛  Bug Aç"
        case .aiChatBugActionSubtitle: return "Jira'da otomatik ticket aç"
        case .aiChatCodeActionTitle: return "🛠️  Kodu Düzenle"
        case .aiChatCodeActionSubtitle: return "Önerilen değişiklikleri gör ve PR oluştur"
        case .aiChatJiraCreating: return "Jira ticket'ı oluşturuluyor..."
        case .aiChatJiraCreated: return "✅ Bug açıldı"
        case .aiChatJiraNoChangeSuffix: return "Claude bu bug için kod değişikliği önermedi."
        case .aiChatJiraChangesBelowSuffix: return "Önerilen değişiklikler aşağıda."
        case .aiChatJiraTicketHeader: return "✅ JIRA TICKET AÇILDI"
        case .aiChatOpenJira: return "🔗 Jira'da Aç"

        case .pokemonHeight: return "Boy"
        case .pokemonWeight: return "Ağırlık"
        case .pokemonStats: return "Statlar"

        case .mealsYoutube: return "YouTube'da İzle"
        case .mealsIngredients: return "Malzemeler"
        case .mealsInstructions: return "Hazırlanışı"
        case .mealsNoInstructions: return "Tarif yok."

        case .countriesOpenMap: return "Haritada Aç"
        case .countriesCapital: return "Başkent"
        case .countriesRegion: return "Bölge"
        case .countriesPopulation: return "Nüfus"
        case .countriesArea: return "Alan"
        case .countriesLanguages: return "Diller"
        case .countriesCurrency: return "Para Birimi"
        case .countriesTimezone: return "Saat Dilimi"
        case .countriesBorders: return "Sınır Komşu"

        case .launchesWebcast: return "Yayını İzle"
        case .launchesArticle: return "Makale"
        case .launchesWikipedia: return "Wikipedia"
        case .launchesFlightFormat: return "Uçuş #{number}"
        }
    }
}
// swiftlint:enable all
